// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAdFvFMGmYCnrIz46dMDfkP3RsQurM7Yaw",
    authDomain: "ipeung-firebase.firebaseapp.com",
    projectId: "ipeung-firebase",
    storageBucket: "ipeung-firebase.firebasestorage.app",
    messagingSenderId: "488611503960",
    appId: "1:488611503960:web:040d36e6abdce2d75e4f2d",
    measurementId: "G-Z602FV4D20",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hpSE_fROPbl6GfrNKnT31ZByq1Z15sY',
    appId: '1:488611503960:android:36298a20d1afd49c5e4f2d',
    messagingSenderId: '488611503960',
    projectId: 'ipeung-firebase',
    storageBucket: 'ipeung-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrf6bbQ-ck5FuC8PVZ46SVJIkTbMyIFzs',
    appId: '1:488611503960:ios:51e0d3b9faac76d65e4f2d',
    messagingSenderId: '488611503960',
    projectId: 'ipeung-firebase',
    storageBucket: 'ipeung-firebase.firebasestorage.app',
    iosBundleId: 'com.example.uasipeung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrf6bbQ-ck5FuC8PVZ46SVJIkTbMyIFzs',
    appId: '1:488611503960:ios:c97c80e9a34bd3685e4f2d',
    messagingSenderId: '488611503960',
    projectId: 'ipeung-firebase',
    storageBucket: 'ipeung-firebase.firebasestorage.app',
    iosBundleId: 'com.example.uasipeung.Runner.Tests',
  );
}
